version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: placement-expo-db
    environment:
      POSTGRES_DB: placement_expo
      POSTGRES_USER: placement_user
      POSTGRES_PASSWORD: placement_password_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - placement-network

  # Application
  app:
    build: .
    container_name: placement-expo-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_URL: jdbc:postgresql://postgres:5432/placement_expo
      DATABASE_USERNAME: placement_user
      DATABASE_PASSWORD: placement_password_dev
      JWT_SECRET: development-jwt-secret-key-very-long-and-secure-for-local-development-only
      APPWRITE_PROJECT_ID: 6894d20300386b659e32
      APPWRITE_ENDPOINT: https://nyc.cloud.appwrite.io/v1
      UPLOAD_DIR: /app/uploads
      CORS_ALLOWED_ORIGINS: http://localhost:8080,http://127.0.0.1:8080
    ports:
      - "8080:8080"
    volumes:
      - upload_data:/app/uploads
      - log_data:/app/logs
    depends_on:
      - postgres
    networks:
      - placement-network
    restart: unless-stopped

volumes:
  postgres_data:
  upload_data:
  log_data:

networks:
  placement-network:
    driver: bridge
