services:
  - type: web
    name: placement-expo
    runtime: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/placement_expo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: placement-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: APPWRITE_PROJECT_ID
        value: 6894d20300386b659e32
      - key: APPWRITE_ENDPOINT
        value: https://nyc.cloud.appwrite.io/v1
      - key: UPLOAD_DIR
        value: /app/uploads
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: PORT
        value: 10000

databases:
  - name: placement-db
    databaseName: placement_expo
    user: placement_user
    plan: free
