services:
  - type: web
    name: placement-expo
    env: node
    plan: free
    buildCommand: |
      # Install Java and Maven using Node.js environment
      curl -s "https://get.sdkman.io" | bash
      source "$HOME/.sdkman/bin/sdkman-init.sh"
      sdk install java 17.0.2-open
      sdk install maven
      # Build with production profile
      mvn clean package -DskipTests -Dspring.profiles.active=render
    startCommand: java -Xmx512m -Dserver.port=$PORT -Dspring.profiles.active=render -jar target/expo-0.0.1-SNAPSHOT.jar
    healthCheckPath: /actuator/health
    numInstances: 1
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: UPLOAD_DIR
        value: /tmp/uploads
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx512m"
      - key: APPWRITE_ENDPOINT
        value: https://nyc.cloud.appwrite.io/v1
      - key: APPWRITE_PROJECT_ID
        value: 6894d20300386b659e32

      - key: JWT_SECRET
        value: placement-expo-jwt-secret-key-very-long-and-secure-for-production-use-minimum-256-bits

      # Spring Boot Configuration
      - key: SERVER_PORT
        value: ${PORT}
      # Database Configuration
      - key: SPRING_DATASOURCE_URL
        value: postgresql://dpg-d2dmdg3uibrs739scu3g-a.oregon-postgres.render.com:5432/placement_expo_db
      - key: SPRING_DATASOURCE_USERNAME
        value: placement_expo_db_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: G8nDOIOGqqYqboucqX3C3sLy04xFho4C
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "false"
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        value: "5"
      - key: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
        value: "2"
